<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>XXXX.CN ｜中国权威潮流网站｜潮流 品牌 互动 购物 社区</title>
<meta property="wb:webmaster" content="678940312cf97365" />
<meta name="Keywords" content="潮流,时尚,潮人,潮牌,品牌，街拍，搭配，流行，购物,blog,部落格,YOHO!潮流志,明星,杂志,设计,音乐,夜生活,服饰,限量,相册,潮流社区,自拍,美眉,正太,帅哥,涂鸦,原创,搭配,明星,日系" />
<meta name="Description" content="YOHO.CN年轻人的城市，中国潮流权威人士聚集地。在这里你可以了解来自全球最新的潮流讯息，预览当季至IN流行时尚搭配风向标。通过最具个性的博客，展示自拍街拍，分享年轻态生活" />
</head>
<body>
<style>
body,div,ul,ol,dl,dt,dd,h1,h2,h3,h4,h5,h6,pre,input,p,blockquote,th,td,button,blockquote{ margin:0; padding:0;}
body{ font-family:宋体,Arial, Verdana;font-size:12px;background:#fff; margin:0; color:#666;text-align:left;}
img {border:0; vertical-align:middle;}
.yh_letter{
	width:680px;
	margin:100px auto;
	font:
}
.yh_letter .letter_icon{
	padding-left:20px;
	border-bottom:1px solid #000;
}
.yh_letter .content{
	padding:30px 0 0 30px
}
.yh_letter .content p{
	font-size:14px; 
	margin-top:15px;
}
.yh_letter .content p.yellow{
	color:#ff5500; 
}
.yh_letter .content p.tips{
	font-size:12px;
	padding-top:20px;
}
.yh_letter .content p.right{
	font-weight:bold;
	text-align:right;
	padding-right:100px;
	margin-top:20px;
}
.yh_letter .content p.right2{
	text-align:right;
	padding-right:100px;
	font-size:12px;
	margin-top:10px;
}
</style>

<!--页头开始-->
<div class="yh_letter">
    <div class="letter_icon">
        <img src="<?php echo $img;?>/ui/logo.gif"/>
    </div>
    <div class="content">
    	<p>亲爱的 <?php echo $email?>:</p>
        <p>欢迎使用XXX找回密码功能。请点击以下链接重置您的密码.（链接48小时内有效） ：</p>
        <p><a href="<?php echo $link?>" target="_blank"><?php echo $link?></a></p>
        <p>如果您没有申请找回密码，请忽略此邮件。</p>
        <p class="tips">这只是一封系统自动发送的邮件，请不要直接回复。</p>
    	<p class="right">XXXX.CN</p>
        <p class="right2"><?php echo date('Y-m-d') ?></p>     
    </div>
</div>


<!--页尾结束-->
</body>
</html>